### ISSUE TITLE
[13pt] Fully deterministic execution of the consensus simulation

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Crypto#1]
## Summary
To remove scheduler randomness from the simulation, we need to enforce fences before actors proceed to the next slot.  Currently the actor system proceeds through slots and method execution and thread interleaving alters the timing of message delivery between actors.  Two simulations with the same initial conditions will have chain data that diverge in a couple of slots.

## Issue Details
- [x] Rework how stakeholders request locks and build tines
- [x] Implement a message priority queue for deterministic ordering of messages between holders
- [x] Have coordinator track current slot instead of system time and increment slot when it has received the ready message from router
- [x] Have router schedule messages in a pseudorandom deterministic order on a slot by slot basis

## Requirements to be considered Done
- [x] Simulation execution should result in a fully deterministic output based on the initial conditions.

**Comment by scasplte2** [comment]
Editing Detail list to include "Rework how stakeholders request blocks and build tines"

**Comment by aaronschutza** [comment]
We now have deterministic execution of the protocol with chronological sorting that maintains the real time causal sequence of events on a slot by slot basis.  This relies on the calculated network latency that's generated by the global network delay model.  When fencing is turned off, the delay is added to the message delivery in real time, relative to the local system time tracked by the coordinator.  With fencing turned on, the delay is used as a key to a map of messages that is sorted and delivered in ascending order.  Messages that are returned and mapped back to a future key, either in the current slot or a future slot if the delay is larger than the slot time minus the highest delivered key.  This ordering maintains a realistic execution of the protocol with zero thread randomness.  The cost is significantly slower execution time of the simulation since the router and stakeholders are waiting for messages most of the time.
