### ISSUE TITLE
[2pt] Documentation: Collect and synthesize all information and research about Prosomo in a wiki page.

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Crypto#15]
The wiki page on the Crypto repository will contain all information and links to data, figures, and literature pertaining to Prosomo research.

**Comment by aaronschutza** [comment]
Wiki has been updated, will continue adding data to Results section as more metrics of chain data are produced.

**Comment by scasplte2** [comment]
Link to the wiki page https://github.com/Topl/Crypto/wiki
