### ISSUE TITLE
[5pt] Development: add an efficient state validity check to isValidChain method to reflect the state validity predicate given in genesis

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Crypto#32]
Tine checking in prosomo currently doesn't check the resulting state induced by an incoming tine before it verifies block by block.  This is counter to what is specified in genesis isValidChain since the state check comes first.  This may be a potential flaw in the implementation of prosomo so the plan is to fix this before moving forward with further tests regarding transactions.

**Comment by scasplte2** [comment]
was completed by modifying the way that block history is handled using a functionality similar to LSMStore.
