### ISSUE TITLE
[3pt] Modify deterministic simulation transaction issue mechanism to more uniformly inject transactions during execution

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Crypto#34]
The round execution in the deterministic protocol operates in such a way that transactions are all issued in one step.  The delay is then dictated by signal propagation speed.  We wish to have random transaction injected uniformly over the course of the round.

**Comment by scasplte2** [comment]
tradeoff of block size vs propagation speed and the economics that might drive decision making

**Comment by aaronschutza** [comment]
Round execution in the deterministic setting has been modified.  There are no longer discrete steps for transaction issuance and chain update.  Transactions are randomly injected into the simulation round by round as messages are delivered.  Chain update is triggered by the stakeholder any time that its block database is added to.  The desired functionality has been implemented and is deterministic but the cost is a higher execution time of the simulation.  Work will continue to make the round execution more efficient and the latest commit will be a reference for the desired functionality.
