### ISSUE TITLE
[8pt] Selfish mining - Implementation

### ISSUE THREAD

**Issue by scasplte2** [Topl/Crypto#42]
**Modeling**
Scenarios to explore
- chain quality vs. attacking stake and delay
---
What is our hypothesis going into this as to how the system should behave?
- expect that there will be a similar fall off in this 2D scan
---
What statement or claim are we evaluating from the published work?

**Comment by aaronschutza** [comment]
Covert mining functionality now works and plotting is to the point where we can produce some convincing visuals
